
CREATE PROCEDURE SP_CARGA_STAGING_PROMOCOES(@DATA DATETIME)
AS
DELETE FROM TB_AUX_PROMOCOES
DECLARE
  @CODIGO INT  ,
  @DESCRICAO VARCHAR(30)  ,
  @DATA_INICIO DATETIME  ,
  @DATA_FIM DATETIME  
DECLARE C_PROMOCOES CURSOR FOR SELECT CODIGO,DESCRICAO, data_inicio, data_fim
						FROM TB_PROMOCOES
  OPEN C_PROMOCOES
  FETCH C_PROMOCOES INTO @CODIGO, @DESCRICAO, @DATA_INICIO, @DATA_FIM
  
  WHILE(@@FETCH_STATUS = 0)
  BEGIN
  INSERT INTO TB_AUX_PROMOCOES (DATA_CARGA,  COD_PROMOCAO, DESCRICAO,DATA_INICIAL,DATA_FINAL)
  VALUES (@DATA, @CODIGO, @DESCRICAO,@DATA_INICIO,@DATA_FIM)
  
  FETCH C_PROMOCOES INTO @CODIGO, @DESCRICAO,@DATA_INICIO,@DATA_FIM
  END
  CLOSE C_PROMOCOES
  DEALLOCATE C_PROMOCOES
						 
