CREATE PROCEDURE SP_CARGA_STAGING_LOJA(@DATA DATETIME)
AS

DELETE FROM TB_AUX_LOJA
DECLARE
	  @COD_LOJA INT,
	  @NOME VARCHAR(20),
	  @REGIAO VARCHAR(20),
	  @ESTADO VARCHAR(20),
	  @CIDADE VARCHAR(20)
	  
	 
DECLARE C_LOJA CURSOR FOR SELECT CODIGO , NOME , REGIAO,
						ESTADO,CIDADE FROM TB_LOJA
						 

  OPEN C_LOJA
  FETCH C_LOJA INTO @COD_LOJA, @NOME, @ESTADO,@CIDADE,@REGIAO
  
  WHILE(@@FETCH_STATUS = 0)
  BEGIN
  INSERT INTO TB_AUX_LOJA (DATA_CARGA, COD_LOJA,NOME,REGIAO, ESTADO, CIDADE)
  VALUES (@DATA,@COD_LOJA,@NOME,@REGIAO,@ESTADO,@CIDADE)
  
  FETCH C_LOJA INTO @COD_LOJA,@NOME,@REGIAO,@ESTADO,@CIDADE
  END
  CLOSE C_LOJA
  DEALLOCATE C_LOJA
						 

