
CREATE PROCEDURE SP_CARGA_STAGING_PRODUTO(@DATA DATETIME)
AS
DELETE FROM TB_AUX_PRODUTO
DECLARE
  @CODIGO INT  ,
  @CODIGO_BARRA INT,
  @DESCRICAO VARCHAR(20)  ,
  @LINHA VARCHAR(20),
  @VALOR NUMERIC(10,2)
DECLARE C_PRODUTO CURSOR FOR SELECT CODIGO, CODIGO_BARRA, DESCRICAO, VALOR
						FROM TB_PRODUTO
  OPEN C_PRODUTO
  FETCH C_PRODUTO INTO @CODIGO, @CODIGO_BARRA, @DESCRICAO, @VALOR
  
  WHILE(@@FETCH_STATUS = 0)
  BEGIN
  INSERT INTO TB_AUX_PRODUTO (DATA_CARGA,  COD, COD_BARRA, DESCRICAO, VALOR)
  VALUES (@DATA, @CODIGO, @CODIGO_BARRA, @DESCRICAO, @VALOR)
  
  FETCH C_PRODUTO INTO  @CODIGO, @CODIGO_BARRA, @DESCRICAO, @VALOR
  END
  CLOSE C_PRODUTO
  DEALLOCATE C_PRODUTO
						 
