
CREATE PROCEDURE SP_CARGA_STAGING_PRODUCAO(@DATA DATETIME)
AS
DELETE FROM TB_AUX_PRODUCAO
DECLARE
  @LOTE INT  ,
  @DESCRICAO VARCHAR(20)  ,
  @DATA_FABRICACAO VARCHAR(20)  
DECLARE C_PRODUCAO CURSOR FOR SELECT LOTE , DESCRICAO, DATA_FABRICACAO						 
						FROM TB_PRODUCAO
  OPEN C_PRODUCAO
  FETCH C_PRODUCAO INTO @LOTE, @DESCRICAO, @DATA_FABRICACAO
  
  WHILE(@@FETCH_STATUS = 0)
  BEGIN
  INSERT INTO TB_AUX_PRODUCAO (DATA_CARGA,  LOTE , DESCRICAO, DATA_FABRICACAO)
  VALUES (@DATA,@LOTE,@DESCRICAO,@DATA_FABRICACAO)
  
  FETCH C_PRODUCAO INTO @LOTE,@DESCRICAO,@DATA_FABRICACAO
  END
  CLOSE C_PRODUCAO
  DEALLOCATE C_PRODUCAO
						 
