/*
CREATE  TABLE TB_AUX_LOJA (
  id_AUX_LOJA INT IDENTITY(1,1) NOT NULL ,
  DATA_CARGA DATETIME NOT NULL ,
  COD_LOJA INT NULL ,
  NOME VARCHAR(20) NULL ,
  CIDADE VARCHAR(20) NULL ,
  ESTADO VARCHAR(20) NULL ,
  REGIAO VARCHAR(20) NULL ,
  PRIMARY KEY (id_AUX_LOJA) )
*/

CREATE PROCEDURE SP_CARGA_STAGING_LOJA(@DATA DATETIME)
AS
DELETE FROM TB_AUX_LOJA
DECLARE
	  @CODIGO INT,
	  @NOME VARCHAR(20),
	  @CIDADE VARCHAR(20),
	  @ESTADO VARCHAR(20),
	  @REGIAO VARCHAR(20)
	 
DECLARE C_LOJA CURSOR FOR SELECT COD_LOJA  ,  NOME ,  CIDADE,
						 ESTADO , REGIAO FROM TB_AUX_LOJA
						 

  OPEN C_LOJA
  FETCH C_LOJA INTO @CODIGO, @NOME, @CIDADE, @ESTADO, @REGIAO
  
  WHILE(@@FETCH_STATUS = 0)
  BEGIN
  INSERT INTO TB_AUX_LOJA (DATA_CARGA, COD_LOJA,NOME,CIDADE,ESTADO,REGIAO)
  VALUES (@DATA,@CODIGO,@NOME,@CIDADE,@ESTADO,@REGIAO)
  
  FETCH C_LOJA INTO @CODIGO,@NOME,@CIDADE,@ESTADO,@REGIAO
  END
  CLOSE C_LOJA
  DEALLOCATE C_LOJA
						 
