
CREATE PROCEDURE SP_CARGA_STAGING_CLIENTE(@DATA DATETIME)
AS
DECLARE
	@CODIGO INT,
	@CPF VARCHAR(11),
	@NOME VARCHAR(30),
	@DATA_NASCIMENTO DATE   ,
	@ENDERECO VARCHAR(45)    ,
	@BAIRRO VARCHAR(20)    ,
	@CIDADE VARCHAR(20)
DECLARE C_CLIENTE CURSOR FOR SELECT CODIGO, CPF, NOME, DATA_NASCIMENTO,
									 ENDERECO, BAIRRO, CIDADE
				FROM TB_CLIENTE				
OPEN C_CLIENTE
FETCH C_CLIENTE INTO @CODIGO, @CPF, @NOME, @DATA_NASCIMENTO, @ENDERECO,
									@BAIRRO, @CIDADE

WHILE (@@FETCH_STATUS = 0)
BEGIN
	INSERT INTO TB_AUX_CLIENTE (DATA_CARGA, COD_CLIENTE, CPF, NOME, DATA_NASCIMENTO,
									 ENDERECO, BAIRRO, CIDADE) 
				VALUES(@DATA,@CODIGO, @CPF, @NOME, @DATA_NASCIMENTO, @ENDERECO,
									@BAIRRO, @CIDADE)
	
FETCH C_CLIENTE INTO	@CODIGO, @CPF, @NOME, @DATA_NASCIMENTO, @ENDERECO,
									@BAIRRO, @CIDADE
	END
	CLOSE C_CLIENTE
	DEALLOCATE C_CLIENTE
	
