insert into TB_Loja values('Ana Cosmeticos','norte','Amazonas', 'Manaus');
insert into TB_Loja values('Beth Cosmeticos','norte','Pará', 'Belém');
insert into TB_Loja values('Cosmeticos & Cia','nordeste','Alagoas', 'Maceió');
insert into TB_Loja values('Perfumes & Cia','nordeste','Sergipe', 'Itabaiana');
insert into TB_Loja values('Maria´s Cosmeticos','nordeste','Sergipe', 'Aracaju');
insert into TB_Loja values('Marieta Perfumaria','nordeste','Sergipe', 'Aracaju');
insert into TB_Loja values('Maria´s Cosmeticos','Sul','Rio Grande do Sul', 'Porto Alegre');
insert into TB_Loja values('Bahia´s Cosmeticos','nordeste','Bahia', 'Salvador');
insert into TB_Loja values('JR Cosmeticos','nordeste','Bahia', 'Salvador');
insert into TB_Loja values('JA Perfumaria','norte','Amazonas', 'Manaus');
insert into TB_Loja values('MG Cosmeticos','norte','Pará', 'Belém');
insert into TB_Loja values('Mariana Cosmeticos','nordeste','Alagoas', 'Maceió');
insert into TB_Loja values('Rei dos Cosmeticos','nordeste','Sergipe', 'Itabaiana');
insert into TB_Loja values('Santos Cosmeticos','nordeste','Sergipe', 'Aracaju');
insert into TB_Loja values('MK Perfumaria','nordeste','Sergipe', 'Aracaju');